theme: jekyll-theme-slate

gems:
  - jekyll-seo-tag
  - jekyll-last-modified-at

plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'